### ISSUE TITLE
Not working on OnePlus One KK

### ISSUE THREAD

**Issue by steve51184** [moneytoo/DeskClockAlarm#2]
I have a OnePlus One running CM 11s 4.4.4

I've installed this mod enabled it and rebooted but the default clock app still doesn't open on the alarms page

**Comment by moneytoo** [comment]
Can you point me to CM 11s source or upload the DeskClock apk?

**Comment by steve51184** [comment]
Sure np

**Comment by moneytoo** [comment]
I don't see any reason why it shouldn't work. Make sure Xposed works for you at all and check Log in Xposed.

**Comment by steve51184** [comment]
A reinstall fixed it thanks :)
